//! The false-positive gate against *real* AUR packages.
//!
//! `e2e_benign.rs` guards hand-written fixtures — shapes somebody thought to
//! write down. This guards a vendored snapshot of the top-50 AUR packages by
//! popularity, which covers the shapes the AUR actually contains. See
//! `fixtures/benign-snapshot/README.md`.
//!
//! **The contract is Blocks-only.** Not one of these packages may Block: they
//! are the most-installed software in the AUR, so a Block is a detector bug
//! until proven otherwise. Do not exempt a package to make this pass — fix the
//! detector. This assertion caught false Blocks on `paru`, `shelly-bin` and
//! `xrizer` the first time it ran.
//!
//! Advisory/Info findings are deliberately *not* asserted. Real packages raise
//! legitimate ones (`spotify` really does fetch over plain HTTP), and a
//! numeric budget over third-party content would only ever get bumped. They
//! are recorded instead — see `record_advisory_snapshot` below.

mod common;

use common::Verdict;

#[test]
fn no_snapshot_package_is_blocked() {
    let mut blocked = Vec::new();
    for name in common::snapshot_packages() {
        let r = common::scan_fixture_dir(&format!("benign-snapshot/{name}"));
        if common::worst(&r) == Verdict::Block || r.exit_code == 2 {
            let why: Vec<String> = r
                .findings
                .iter()
                .filter(|f| f.severity >= common::Severity::High)
                .map(|f| format!("{}: {}", f.detector, f.reason))
                .collect();
            blocked.push(format!("  {name}\n    {}", why.join("\n    ")));
        }
    }
    assert!(
        blocked.is_empty(),
        "aurscan Blocks {} popular AUR package(s) — treat as a detector false \
         positive, not a fixture to exempt:\n{}",
        blocked.len(),
        blocked.join("\n")
    );
}

/// Rewrite `fixtures/benign-snapshot/ADVISORIES.json`, the reviewable record of
/// what the corpus raises below Block level.
///
/// Ignored by default: a test that writes into the source tree on every
/// `cargo test` would dirty the worktree and race under the parallel runner.
/// Run it deliberately after a detector change and review the diff:
///
///     cargo test -p aurscan --test e2e_benign_snapshot -- --ignored
#[test]
#[ignore = "writes into the source tree; run deliberately"]
fn record_advisory_snapshot() {
    use serde_json::json;
    use std::collections::BTreeMap;

    let mut entries = Vec::new();
    let mut totals: BTreeMap<String, usize> = BTreeMap::new();
    for name in common::snapshot_packages() {
        let r = common::scan_fixture_dir(&format!("benign-snapshot/{name}"));
        if r.findings.is_empty() {
            continue;
        }
        let mut by_rule: BTreeMap<String, usize> = BTreeMap::new();
        for f in &r.findings {
            let rule = format!(
                "{}/{}",
                f.detector,
                format!("{:?}", f.severity).to_lowercase()
            );
            *by_rule.entry(rule.clone()).or_default() += 1;
            *totals.entry(rule).or_default() += 1;
        }
        entries.push(json!({
            "package": name,
            "verdict": format!("{:?}", common::worst(&r)).to_lowercase(),
            "findings": r.findings.len(),
            "by_rule": by_rule,
        }));
    }

    let doc = json!({
        "_comment": "Generated by `cargo test --test e2e_benign_snapshot -- --ignored`. \
                     Advisory/Info findings are NOT asserted: this is a reviewable record \
                     of detector noise against real AUR packages, not a budget. Only the \
                     zero-Blocks assertion gates.",
        "totals_by_rule": totals,
        "packages_with_findings": entries,
    });
    let path = common::fixtures_root().join("benign-snapshot/ADVISORIES.json");
    std::fs::write(&path, serde_json::to_string_pretty(&doc).unwrap() + "\n")
        .expect("write ADVISORIES.json");
    eprintln!("wrote {}", path.display());
}
